# Generated by Django 5.0.2 on 2024-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
