# Generated by Django 5.0.2 on 2024-03-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_book_bus_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
