# Generated by Django 5.0.2 on 2024-03-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_book_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
