# Generated by Django 5.0.2 on 2024-03-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_coffee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Payment',
        ),
    ]
