# Generated by Django 5.0.2 on 2024-04-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_routes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='routes',
        ),
    ]
