# Generated by Django 5.0.2 on 2024-04-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_routess'),
    ]

    operations = [
        migrations.CreateModel(
            name='pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_title', models.CharField(max_length=120)),
                ('pack_rating', models.CharField(max_length=120)),
                ('pack_des', models.TextField()),
            ],
        ),
    ]
