# Generated by Django 5.0.2 on 2024-04-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(upload_to='')),
                ('client_name', models.CharField(max_length=100)),
                ('client_date', models.DateField()),
                ('client_title', models.CharField(max_length=100)),
                ('client_des', models.TextField()),
            ],
        ),
    ]
