# Generated by Django 5.0.2 on 2024-04-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='')),
                ('about_title', models.CharField(max_length=120)),
                ('about_des', models.TextField()),
            ],
        ),
    ]
