# Generated by Django 5.0.2 on 2024-04-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_abouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouts',
            name='about_image',
        ),
    ]
