# Generated by Django 5.0.2 on 2024-04-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_abouts_about_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abouts',
        ),
    ]
